"""Public domain contract for Phase 7 resume builder."""

from .entities import (
    ResumeAuditAction,
    ResumeBuilderAuditEvent,
    ResumeBuilderIdempotencyRecord,
    ResumeBullet,
    ResumeDocument,
    ResumeDownloadIntent,
    ResumeExport,
    ResumeExportStatus,
    ResumeFormat,
    ResumeSection,
    ResumeTemplate,
    ResumeVerificationReport,
    ResumeVerificationStatus,
    ResumeVersion,
)
from .errors import (
    ResumeBuilderConflict,
    ResumeBuilderError,
    ResumeBuilderIdempotencyConflict,
    ResumeBuilderNotFound,
    ResumeBuilderUnavailable,
    ResumeBuilderValidationError,
    ResumeBuilderVersionConflict,
    ResumeExportBlocked,
)
from .validation import (
    MAX_BULLET_LENGTH,
    MAX_ITEMS_PER_SECTION,
    MAX_SECTION_KIND_LENGTH,
    MAX_SECTION_TITLE_LENGTH,
    MAX_SECTIONS,
    MAX_TARGET_ROLE_LENGTH,
    MAX_TITLE_LENGTH,
    normalize_text,
    validate_optional_target_role,
    validate_sections,
    validate_title,
)

__all__ = [
    "MAX_BULLET_LENGTH",
    "MAX_ITEMS_PER_SECTION",
    "MAX_SECTIONS",
    "MAX_SECTION_KIND_LENGTH",
    "MAX_SECTION_TITLE_LENGTH",
    "MAX_TARGET_ROLE_LENGTH",
    "MAX_TITLE_LENGTH",
    "ResumeAuditAction",
    "ResumeBuilderAuditEvent",
    "ResumeBuilderConflict",
    "ResumeBuilderError",
    "ResumeBuilderIdempotencyConflict",
    "ResumeBuilderIdempotencyRecord",
    "ResumeBuilderNotFound",
    "ResumeBuilderUnavailable",
    "ResumeBuilderValidationError",
    "ResumeBuilderVersionConflict",
    "ResumeBullet",
    "ResumeDocument",
    "ResumeDownloadIntent",
    "ResumeExport",
    "ResumeExportBlocked",
    "ResumeExportStatus",
    "ResumeFormat",
    "ResumeSection",
    "ResumeTemplate",
    "ResumeVerificationReport",
    "ResumeVerificationStatus",
    "ResumeVersion",
    "normalize_text",
    "validate_optional_target_role",
    "validate_sections",
    "validate_title",
]
