"""Independent bounded extractor adapter for Rezumi-generated resume exports."""

from __future__ import annotations

import asyncio
import stat
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from zipfile import BadZipFile, ZipFile

from docx import Document
from pypdf import PdfReader

from rezumi.modules.resume_builder.application import ExtractedDocumentText
from rezumi.modules.resume_builder.application.ports import ResumeDocumentExtractor

PARSER_VERSION = "rezumi-resume-export-verifier/1.0.0"
_BIDI_CONTROLS = dict.fromkeys(
    [
        *range(0x202A, 0x202F),
        *range(0x2066, 0x206A),
        0x200E,
        0x200F,
        0x061C,
    ]
)
# ReportLab bullet glyphs and other layout controls should not survive verification.
_EXPORT_CONTROL_CHARS = dict.fromkeys([*range(0x20), 0x7F, *range(0x80, 0xA0)])


@dataclass(frozen=True, slots=True)
class ResumeExportExtractionLimits:
    """Resource limits for independently parsing generated resume files."""

    max_bytes: int
    max_pdf_pages: int
    max_archive_entries: int
    max_archive_uncompressed_bytes: int
    max_archive_ratio: int
    processing_timeout_seconds: float
    max_extracted_characters: int = 500_000
    max_extracted_blocks: int = 10_000


class ResumeExportExtractionError(ValueError):
    """Content-free failure raised when generated bytes cannot be parsed safely."""


class ResumeBuilderDocumentExtractor(ResumeDocumentExtractor):
    """Parse PDF/DOCX bytes without depending on another product module."""

    def __init__(self, limits: ResumeExportExtractionLimits) -> None:
        self._limits = limits

    async def extract(self, path: Path, media_type: str) -> ExtractedDocumentText:
        try:
            return await asyncio.wait_for(
                asyncio.to_thread(self._extract, path, media_type),
                self._limits.processing_timeout_seconds,
            )
        except TimeoutError as exc:
            raise ResumeExportExtractionError("resume_export_extraction_timeout") from exc

    def _extract(self, path: Path, media_type: str) -> ExtractedDocumentText:
        if path.stat().st_size > self._limits.max_bytes:
            raise ResumeExportExtractionError("resume_export_too_large")
        if media_type == "application/pdf":
            return self._extract_pdf(path)
        if media_type == "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
            return self._extract_docx(path)
        raise ResumeExportExtractionError("unsupported_resume_export_type")

    def _extract_pdf(self, path: Path) -> ExtractedDocumentText:
        raw = path.read_bytes()
        if not raw[:1024].startswith(b"%PDF-"):
            raise ResumeExportExtractionError("resume_export_signature_mismatch")
        if b"PK\x03\x04" in raw:
            raise ResumeExportExtractionError("resume_export_polyglot_rejected")
        if b"%%EOF" not in raw[-2048:]:
            raise ResumeExportExtractionError("malformed_resume_export_pdf")
        try:
            reader = PdfReader(str(path), strict=False)
            if reader.is_encrypted:
                raise ResumeExportExtractionError("encrypted_resume_export")
            if not 1 <= len(reader.pages) <= self._limits.max_pdf_pages:
                raise ResumeExportExtractionError("resume_export_page_limit_exceeded")
            page_texts: list[str] = []
            removed_bidi = False
            for page in reader.pages:
                value, removed = _sanitize((page.extract_text() or "").replace("\x00", ""))
                page_texts.append(value)
                removed_bidi = removed_bidi or removed
        except ResumeExportExtractionError:
            raise
        except Exception as exc:
            raise ResumeExportExtractionError("malformed_resume_export_pdf") from exc

        plain_text = "\n\f\n".join(page_texts).strip()
        self._check_text_size(plain_text)
        warnings = _warnings(plain_text, removed_bidi)
        return ExtractedDocumentText(
            plain_text=plain_text,
            reading_order=_reading_order(
                page_texts,
                max_blocks=self._limits.max_extracted_blocks,
            ),
            parser_version=PARSER_VERSION,
            warnings=warnings,
            page_count=len(page_texts),
        )

    def _extract_docx(self, path: Path) -> ExtractedDocumentText:
        raw = path.read_bytes()
        if not raw.startswith(b"PK\x03\x04"):
            raise ResumeExportExtractionError("resume_export_signature_mismatch")
        if b"%PDF-" in raw:
            raise ResumeExportExtractionError("resume_export_polyglot_rejected")
        self._validate_docx_archive(path)
        try:
            document = Document(str(path))
            values: list[str] = []
            removed_bidi = False
            for paragraph in document.paragraphs:
                value, removed = _sanitize(paragraph.text.replace("\x00", ""))
                if value.strip():
                    values.append(value.strip())
                removed_bidi = removed_bidi or removed
            for table in document.tables:
                for row in table.rows:
                    raw_value = " | ".join(
                        cell.text.replace("\x00", "").strip() for cell in row.cells
                    )
                    value, removed = _sanitize(raw_value)
                    if value.strip(" |"):
                        values.append(value)
                    removed_bidi = removed_bidi or removed
        except Exception as exc:
            raise ResumeExportExtractionError("malformed_resume_export_docx") from exc

        plain_text = "\n".join(values)
        self._check_text_size(plain_text)
        if len(values) > self._limits.max_extracted_blocks:
            raise ResumeExportExtractionError("resume_export_block_limit_exceeded")
        return ExtractedDocumentText(
            plain_text=plain_text,
            reading_order=tuple(values),
            parser_version=PARSER_VERSION,
            warnings=_warnings(plain_text, removed_bidi),
            page_count=1,
        )

    def _validate_docx_archive(self, path: Path) -> None:
        try:
            with ZipFile(path) as archive:
                infos = archive.infolist()
                if len(infos) > self._limits.max_archive_entries:
                    raise ResumeExportExtractionError("resume_export_archive_entry_limit")
                total_uncompressed = 0
                total_compressed = 0
                names: set[str] = set()
                for info in infos:
                    normalized = PurePosixPath(info.filename.replace("\\", "/"))
                    if normalized.is_absolute() or ".." in normalized.parts:
                        raise ResumeExportExtractionError("resume_export_archive_traversal")
                    mode = info.external_attr >> 16
                    if mode and stat.S_ISLNK(mode):
                        raise ResumeExportExtractionError("resume_export_archive_symlink")
                    if info.flag_bits & 0x1:
                        raise ResumeExportExtractionError("encrypted_resume_export")
                    total_uncompressed += info.file_size
                    total_compressed += max(1, info.compress_size)
                    names.add(info.filename.casefold())
                if total_uncompressed > self._limits.max_archive_uncompressed_bytes:
                    raise ResumeExportExtractionError("resume_export_archive_expansion_limit")
                if total_uncompressed > total_compressed * self._limits.max_archive_ratio:
                    raise ResumeExportExtractionError("resume_export_archive_ratio_limit")
                if "word/vbaproject.bin" in names or any("macroenabled" in name for name in names):
                    raise ResumeExportExtractionError("resume_export_macro_rejected")
                if "[content_types].xml" not in names or "word/document.xml" not in names:
                    raise ResumeExportExtractionError("invalid_resume_export_docx")
                if archive.testzip() is not None:
                    raise ResumeExportExtractionError("malformed_resume_export_docx")
        except ResumeExportExtractionError:
            raise
        except (BadZipFile, OSError) as exc:
            raise ResumeExportExtractionError("malformed_resume_export_docx") from exc

    def _check_text_size(self, plain_text: str) -> None:
        if len(plain_text) > self._limits.max_extracted_characters:
            raise ResumeExportExtractionError("resume_export_text_limit_exceeded")


def _reading_order(page_texts: list[str], *, max_blocks: int) -> tuple[str, ...]:
    values = tuple(
        line
        for page_text in page_texts
        for raw_line in page_text.splitlines()
        if (line := raw_line.strip())
    )
    if len(values) > max_blocks:
        raise ResumeExportExtractionError("resume_export_block_limit_exceeded")
    return values


def _sanitize(value: str) -> tuple[str, bool]:
    sanitized = value.translate(_BIDI_CONTROLS).translate(_EXPORT_CONTROL_CHARS)
    return sanitized, sanitized != value


def _warnings(plain_text: str, removed_bidi: bool) -> tuple[str, ...]:
    values: list[str] = []
    if len(plain_text.strip()) < 40:
        values.append("limited_extractable_text")
    if removed_bidi:
        values.append("bidirectional_controls_removed")
    return tuple(values)
