"""Public Role Readiness domain contract."""

from .entities import (
    CompetencyDimension,
    CompetencyEvidenceLink,
    CompetencyImportance,
    CompetencyResult,
    ReadinessComponent,
    ReadinessLabel,
    RoleAuditAction,
    RoleCompetency,
    RoleDefinition,
    RoleReadinessAnalysis,
    RoleReadinessAuditEvent,
    RoleSeniority,
    RoleTaxonomyVersion,
    SavedRole,
    SkillMatchState,
)
from .errors import (
    RoleReadinessConflict,
    RoleReadinessError,
    RoleReadinessIdempotencyConflict,
    RoleReadinessNotFound,
    RoleReadinessUnavailable,
    RoleReadinessValidationError,
    RoleReadinessVersionConflict,
)
from .scoring import (
    CONFIGURATION_VERSION,
    ENGINE_VERSION,
    FEATURE_SCHEMA_VERSION,
    CareerReadinessSnapshot,
    CompetencyMatch,
    ComponentScore,
    EvidenceMatch,
    SnapshotEntity,
    SnapshotEvidence,
    SnapshotSkill,
    score_role_readiness,
)

__all__ = [
    "CONFIGURATION_VERSION",
    "ENGINE_VERSION",
    "FEATURE_SCHEMA_VERSION",
    "CareerReadinessSnapshot",
    "CompetencyDimension",
    "CompetencyEvidenceLink",
    "CompetencyImportance",
    "CompetencyMatch",
    "CompetencyResult",
    "ComponentScore",
    "EvidenceMatch",
    "ReadinessComponent",
    "ReadinessLabel",
    "RoleAuditAction",
    "RoleCompetency",
    "RoleDefinition",
    "RoleReadinessAnalysis",
    "RoleReadinessAuditEvent",
    "RoleReadinessConflict",
    "RoleReadinessError",
    "RoleReadinessIdempotencyConflict",
    "RoleReadinessNotFound",
    "RoleReadinessUnavailable",
    "RoleReadinessValidationError",
    "RoleReadinessVersionConflict",
    "RoleSeniority",
    "RoleTaxonomyVersion",
    "SavedRole",
    "SkillMatchState",
    "SnapshotEntity",
    "SnapshotEvidence",
    "SnapshotSkill",
    "score_role_readiness",
]
